WINDOW_HOURS = 24
MAX_POSTS_PER_SOURCE = 50
MAX_COMMENTS_PER_POST = 100
DELAY_SECONDS = 3

DEFAULT_ACCESS_STATUS = "PUBLIC_ACCESSIBLE"
LOGIN_REQUIRED_STATUS = "LOGIN_REQUIRED"
BLOCKED_STATUS = "BLOCKED"
NOT_FOUND_STATUS = "NOT_FOUND"
ERROR_STATUS = "ERROR"
